[Variables]
BackgroundColor = 0,0,0
BackgroundOpacity = 120
BackgroundRadius=30

BackgroundBorderSize=1
BackgroundBorderColor=0,0,0
BackgroundBorderOpacity=#BackgroundOpacity#

BackgroundPadding=90

BackgroundPaddingLeft=#BackgroundPadding#
BackgroundPaddingRight=#BackgroundPadding#
BackgroundPaddingTop=#BackgroundPadding#
BackgroundPaddingBottom=#BackgroundPadding#

BackgroundEffect=None