[Variables]
Scale = 1.5
Orientation = 1
PosX = 0
PosY = 0

ShellColor = 255, 255, 255

DefaultPercentageColor = 255, 255, 255
ChargingColor = 33, 153, 161
HighColor = 195, 246, 105
MiddleColor = 207, 146, 79
LowColor = 219, 45, 52

ShellOpacity = 230
PercentageOpacity = 245

ShellWidth = 550
ShellHeight = 290
ShellThickness = 30

OuterRadius = 55
InnerRadius = 30
PercentageRadius = 20

PercentageSpacing = 20

HidePole = 0
PoleWidth = 100
PoleHeight = 30
PoleRadius = 14
PoleTransitionRadius = 12
SmoothPoleTransition = 1